/**
 * SimulationPdfExport.tsx — PDF Export utility for Operations Simulation
 * Uses jsPDF text API directly (no html2canvas) to avoid oklch() Tailwind v4 errors
 */
import { jsPDF } from 'jspdf';

// ─── Types ────────────────────────────────────────────────────────────────────
export interface PdfSection {
  title: string;
  rows: { label: string; value: string }[];
}

export interface PdfExportConfig {
  scenarioTitle: string;
  scenarioDesc: string;
  parameters: { label: string; value: string }[];
  kpiResults: { label: string; value: string; status?: 'good' | 'warning' | 'bad' }[];
  sections: PdfSection[];
  recommendations: string[];
  riskLevel?: string;
}

// ─── Formatter ────────────────────────────────────────────────────────────────
const today = () => {
  const d = new Date();
  return `${d.getDate().toString().padStart(2, '0')}/${(d.getMonth() + 1).toString().padStart(2, '0')}/${d.getFullYear()}`;
};

// ─── Generate PDF ─────────────────────────────────────────────────────────────
export function generateSimulationPdf(config: PdfExportConfig) {
  const doc = new jsPDF('p', 'mm', 'a4');
  const W = 210;
  const margin = 15;
  const contentW = W - margin * 2;
  let y = margin;

  const addPage = () => {
    doc.addPage();
    y = margin;
  };

  const checkPage = (needed: number) => {
    if (y + needed > 280) addPage();
  };

  // ─── Header ─────────────────────────────────────────────────────────────
  doc.setFillColor(30, 58, 138); // blue-900
  doc.rect(0, 0, W, 38, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('HCMS — Operations Simulation Report', margin, 14);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(config.scenarioTitle, margin, 22);
  doc.setFontSize(8);
  doc.text(`Tanggal: ${today()}  |  Dokumen: RAHASIA / INTERNAL`, margin, 30);
  doc.text('Generated by HCMS Simulation Engine', W - margin - 70, 30);
  y = 45;

  // ─── Scenario Description ──────────────────────────────────────────────
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  const descLines = doc.splitTextToSize(config.scenarioDesc, contentW);
  doc.text(descLines, margin, y);
  y += descLines.length * 4 + 4;

  // Risk Level badge
  if (config.riskLevel) {
    doc.setFontSize(9);
    doc.setFont('helvetica', 'bold');
    const riskColors: Record<string, [number, number, number]> = {
      'RISIKO RENDAH': [34, 197, 94],
      'RISIKO SEDANG': [245, 158, 11],
      'RISIKO TINGGI': [249, 115, 22],
      'RISIKO KRITIS': [239, 68, 68],
    };
    const rc = riskColors[config.riskLevel] || [100, 100, 100];
    doc.setFillColor(rc[0], rc[1], rc[2]);
    doc.roundedRect(margin, y, 45, 6, 1.5, 1.5, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(7);
    doc.text(config.riskLevel, margin + 3, y + 4.2);
    y += 12;
  }

  // ─── Parameters ─────────────────────────────────────────────────────────
  doc.setTextColor(30, 58, 138);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Parameter Simulasi', margin, y);
  y += 2;
  doc.setDrawColor(30, 58, 138);
  doc.setLineWidth(0.5);
  doc.line(margin, y, margin + contentW, y);
  y += 5;

  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  const paramColW = contentW / 2;
  config.parameters.forEach((p, i) => {
    const col = i % 2;
    const xOff = margin + col * paramColW;
    if (col === 0 && i > 0) y += 5;
    checkPage(8);
    doc.setFont('helvetica', 'normal');
    doc.text(p.label + ':', xOff, y);
    doc.setFont('helvetica', 'bold');
    doc.text(p.value, xOff + 50, y);
  });
  if (config.parameters.length % 2 !== 0) y += 5;
  y += 8;

  // ─── KPI Results ────────────────────────────────────────────────────────
  checkPage(30);
  doc.setTextColor(30, 58, 138);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text('Hasil Simulasi (KPI)', margin, y);
  y += 2;
  doc.line(margin, y, margin + contentW, y);
  y += 5;

  const kpiColW = contentW / Math.min(config.kpiResults.length, 4);
  config.kpiResults.forEach((kpi, i) => {
    const col = i % 4;
    if (col === 0 && i > 0) y += 14;
    checkPage(18);
    const xOff = margin + col * kpiColW;

    // Status color
    const statusColors: Record<string, [number, number, number]> = {
      good: [34, 197, 94],
      warning: [245, 158, 11],
      bad: [239, 68, 68],
    };
    const sc = statusColors[kpi.status || 'good'] || [60, 60, 60];
    doc.setFillColor(sc[0], sc[1], sc[2]);
    doc.circle(xOff + 2, y + 1, 1.5, 'F');

    doc.setTextColor(sc[0], sc[1], sc[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(kpi.value, xOff + 6, y + 2);
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(kpi.label, xOff + 6, y + 7);
  });
  y += 18;

  // ─── Detail Sections ───────────────────────────────────────────────────
  config.sections.forEach(section => {
    checkPage(20);
    doc.setTextColor(30, 58, 138);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(section.title, margin, y);
    y += 2;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentW, y);
    y += 4;

    // Table header
    doc.setFillColor(243, 244, 246);
    doc.rect(margin, y - 2, contentW, 6, 'F');
    doc.setFontSize(7);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(100, 100, 100);
    doc.text('Item', margin + 2, y + 2);
    doc.text('Nilai', margin + contentW - 50, y + 2);
    y += 7;

    section.rows.forEach((row, ri) => {
      checkPage(6);
      if (ri % 2 === 0) {
        doc.setFillColor(249, 250, 251);
        doc.rect(margin, y - 3, contentW, 5.5, 'F');
      }
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(60, 60, 60);
      doc.setFontSize(7);
      doc.text(row.label, margin + 2, y);
      doc.setFont('helvetica', 'bold');
      doc.text(row.value, margin + contentW - 50, y);
      y += 5.5;
    });
    y += 5;
  });

  // ─── Recommendations ───────────────────────────────────────────────────
  checkPage(25);
  doc.setTextColor(30, 58, 138);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text('Rekomendasi', margin, y);
  y += 2;
  doc.line(margin, y, margin + contentW, y);
  y += 5;

  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(60, 60, 60);
  config.recommendations.forEach((rec, i) => {
    checkPage(8);
    const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, contentW - 5);
    doc.text(lines, margin + 2, y);
    y += lines.length * 3.8 + 2;
  });

  // ─── Footer ─────────────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(6);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(180, 180, 180);
    doc.text(`HCMS Simulation Engine — ${config.scenarioTitle} — Halaman ${p}/${pageCount}`, margin, 292);
    doc.text('RAHASIA / INTERNAL — Hanya untuk keperluan manajemen RS', W - margin - 80, 292);
  }

  // Save
  const filename = `Simulasi_${config.scenarioTitle.replace(/\s+/g, '_')}_${today().replace(/\//g, '-')}.pdf`;
  doc.save(filename);
}

// ─── PDF Button Component ─────────────────────────────────────────────────────
import React from 'react';
import { FileDown } from 'lucide-react';

export function PdfExportButton({ onClick, label = 'Export PDF' }: { onClick: () => void; label?: string }) {
  return (
    <button onClick={onClick}
      className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-blue-600 bg-blue-50 border border-blue-200 rounded-lg hover:bg-blue-100 transition-colors">
      <FileDown className="w-3.5 h-3.5" />
      {label}
    </button>
  );
}
